//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class basket
    {
        public int id_basket { get; set; }
        public int id_user { get; set; }
        public int id_product { get; set; }
        public int quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
